---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-nginx
  labels:
    deployment: helm
    name: ingress-nginx
    tier: cluster
  annotations:
    argocd.argoproj.io/sync-wave: "-50"
spec:
  project: cluster-addons
  source:
    repoURL: https://kubernetes.github.io/ingress-nginx
    chart: ingress-nginx
    targetRevision: 4.2.5
  destination:
    server: https://kubernetes.default.svc
    namespace: ingress-nginx
  syncPolicy:
    syncOptions:
    - CreateNamespace=true