---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  labels:
    deployment: helm
    name: cert-manager
    tier: cluster
  annotations:
    argocd.argoproj.io/sync-wave: "-60"
spec:
  project: cluster-addons
  source:
    repoURL: https://charts.jetstack.io
    chart: cert-manager
    targetRevision: v1.9.1
    helm:
      parameters:
      - name: installCRDs
        value: "true"
  destination:
    server: https://kubernetes.default.svc
    namespace: cert-manager
  syncPolicy:
    syncOptions:
    - CreateNamespace=true