---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: opa-gatekeeper
  labels:
    deployment: helm
    name: opa-gatekeeper
    tier: cluster
  annotations:
    argocd.argoproj.io/sync-wave: "-70"
spec:
  project: cluster-addons
  source:
    repoURL: https://open-policy-agent.github.io/gatekeeper/charts
    chart: gatekeeper
    targetRevision: 3.9.0
  destination:
    server: https://kubernetes.default.svc
    namespace: gatekeeper-system
  syncPolicy:
    syncOptions:
    - CreateNamespace=true