---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: istio-base
  labels:
    deployment: helm
    name: istio-base
    tier: cluster
  annotations:
    argocd.argoproj.io/sync-wave: "-100"
spec:
  generators: []
  template:
    metadata:
      name: istio-base-replaceme
      labels:
        deployment: helm
        name: istio-base
        tier: cluster
      annotations:
        argocd.argoproj.io/sync-wave: "-50"
    project: cluster-addons
    source:
      repoURL: https://istio-release.storage.googleapis.com/charts
      chart: base
      targetRevision: 1.15.0
    destination:
      server: https://kubernetes.default.svc
      namespace: istio-system
    syncPolicy:
      syncOptions:
      - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: istiod
  labels:
    deployment: helm
    name: istiod
    tier: cluster
  annotations:
    argocd.argoproj.io/sync-wave: "-100"
spec:
  generators: []
  template:
    metadata:
      name: istiod-replaceme
      labels:
        deployment: helm
        name: istiod
        tier: cluster
      annotations:
        argocd.argoproj.io/sync-wave: "-45"
    project: cluster-addons
    source:
      repoURL: https://istio-release.storage.googleapis.com/charts
      chart: istiod
      targetRevision: 1.15.0
    destination:
      server: https://kubernetes.default.svc
      namespace: istio-system
    syncPolicy:
      syncOptions:
      - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: istio-internal-ingress
  labels:
    deployment: helm
    name: istio-internal-ingress
    tier: cluster
  annotations:
    argocd.argoproj.io/sync-wave: "-100"
spec:
  generators: []
  template:
    metadata:
      name: istio-internal-ingress
      labels:
        deployment: helm
        name: istio-internal-ingress
        tier: cluster
      annotations:
        argocd.argoproj.io/sync-wave: "-40"
    project: cluster-addons
    source:
      repoURL: https://istio-release.storage.googleapis.com/charts
      chart: gateway
      targetRevision: 1.15.0
      helm:
        parameters:
        - name: service.type
          value: ClusterIP
    destination:
      server: https://kubernetes.default.svc
      namespace: istio-ingress
    syncPolicy:
      syncOptions:
      - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: istio-external-ingress
  labels:
    deployment: helm
    name: istio-external-ingress
    tier: cluster
  annotations:
    argocd.argoproj.io/sync-wave: "-100"
spec:
  generators: []
  template:
    metadata:
      name: istio-external-ingress
      labels:
        deployment: helm
        name: istio-external-ingress
        tier: cluster
      annotations:
        argocd.argoproj.io/sync-wave: "-40"
    project: cluster-addons
    source:
      repoURL: https://istio-release.storage.googleapis.com/charts
      chart: gateway
      targetRevision: 1.15.0
    destination:
      server: https://kubernetes.default.svc
      namespace: istio-ingress
    syncPolicy:
      syncOptions:
      - CreateNamespace=true